"""Add material photo and description fields to Order model

Revision ID: 94983354f88f
Revises: 41b5db8374eb
Create Date: 2025-10-11 10:39:44.222198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94983354f88f'
down_revision = '41b5db8374eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_photo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('material_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('material_description')
        batch_op.drop_column('material_photo_url')

    # ### end Alembic commands ###
